In [3]:
import numpy as np

In [4]:
x = 1.0+0.5j
print(x.real)
print(x.imag)

1.0
0.5


In [5]:
print(x.conjugate())
print(np.conj(x))

(1-0.5j)
(1-0.5j)


In [10]:
import numpy as np
umat = [[1,2,3],[4,3,1],[4,5,6]]
eigvals, eigecs = np.linalg.eig(umat)
print(f"{eigvals}")
print(f"\n{eigecs}")


[ 9.76368965 -0.44860892  0.68491927]

[[ 0.37374956  0.60545305  0.3381653 ]
 [ 0.34814032 -0.76545705 -0.79903755]
 [ 0.85971483  0.2179498   0.49717524]]
